name: CI Pipeline

# Aciona o build em cada commit ou pull request nas branches main ou develop
on:
  push:
    branches:
      - main
      - feature
      - hotfix
  pull_request:
    branches:
      - main
      - feature
      - hotfix

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out do codigo
      uses: actions/checkout@v3

    - name: Versao do Python 
      uses: actions/setup-python@v5
      with:
        python-version: '3.11.4'

    # Instala as dependências
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest
        pip install pytest-mock

    # Executa os testes
    - name: Run Tests
      run: |
        pytest 

    # Opcional: Executa linters para garantir a qualidade do código
    #- name: Run linters
    #  run: |
    #    flake8 .
