name: CI Pipeline

# Aciona o build em cada commit ou pull request nas branches main ou develop
on:
  push:
    branches:
      - main
      - feature
      - hotfix
  pull_request:
    branches:
      - main
      - feature
      - hotfix

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    # Faz checkout do código no repositório
    - name: Check out code
      uses: actions/checkout@v3

    # Configura a versão do Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    # Instala as dependências
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Executa os testes
    - name: Run Tests
      run: |
        pytest

    # Opcional: Executa linters para garantir a qualidade do código
    - name: Run linters
      run: |
        flake8 .
